# Generated by Django 2.2.10 on 2020-03-02 01:56

import devices.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=devices.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('category', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=10)),
                ('lng', models.FloatField(max_length=10)),
                ('x_acc', models.FloatField(max_length=10)),
                ('y_acc', models.FloatField(max_length=10)),
                ('z_acc', models.FloatField(max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='devices.devices')),
            ],
        ),
    ]
